### PR TITLE
Updates base_chart.rb to insert "google.charts.load" instead of "google.load". Updates GanttChart class to Gantt.

### PR DESCRIPTION
**Pull request by kyleoliveira**
GanttChart isn't working as specified given the current Google Charts API. This seems to get it working again.

### CODE REVIEW

**Comment by winston** [comment]
@kyleoliveira Thanks for the PR! The gantt chart fix is good. The `google.charts.load` fix probably needs a bit more work though. According to https://developers.google.com/chart/interactive/docs/basic_load_libs#frozen-versions, it seems like it's not only that `google.load` has changed, but the params to it has been updated too.

Would you like to take a crack at that? Otherwise, I can only look at it end of the week or the following week.

Thanks!

**Comment by kyleoliveira** [comment]
Ah, interesting. I don't know if I'm going to have to do that this week (doesn't look too bad, though), but if I can I'll update the PR (assuming you're not going to merge until the params are fixed) and put a comment in about it. Otherwise, go for it when you get a chance. I don't think a week or two will hold up anything on our end :wink:.

Thanks for making this gem, by the way! So far it's looking like it's going to make things a lot easier for our project.

**Comment by kyleoliveira** [comment]
Juuuuuust kidding - almost sorted it over breakfast. There is one issue though. According to https://developers.google.com/chart/interactive/docs/basic_load_libs#basic-library-loading , you can only call google.charts.load() once and you're supposed to append the list of all packages needed on the page instead of just the one that we're doing now every time the chart is inserted.

I think I'd need a bit more time to sort out the right way to do that. If I was going to try, it almost feels like maybe the library should provide a helper or something inserts the include for the library and the google.charts.load for all packages on the page. Presumably the user would pass in the package list unless there's an easy way to grab all chart object from the page already, in which case I suppose this would be even easier to automate.

How would you like to go from here? As-is, this works as advertised with the limitation that you can only have one chart per page.

**Comment by kyleoliveira** [comment]
I finally got some more time to work on this. I've refactored the helper method so that you can either use it as before, or you can use separate methods to load the libraries and load the chart callback. In the latter case, you'll now be able to load all the libraries you need for a given page as specified on that API page I mentioned earlier.

It's not going to pass Travis yet because I haven't updated the tests accordingly. Is this how you'd like to go with this? If so I can take a whack at the tests (or you could write them or just merge it if you want).

**Comment by kyleoliveira** [comment]
I've updated the tests to handle the new changes. @winston what do you think?

**Comment by flexloop** [comment]
Hi All-

I can't get the gantt to work even with the updates above in 35ed317.

Do either of you have a version that currently works?

I also don't seem to get the syntax correct to pull a specific commit from the repository by commit.

Thanks-

Michael

**Comment by Insood** [comment]
@kyleoliveira @winston 

Looks like the limitations don't exist anymore in versions past v47?

https://developers.google.com/chart/interactive/docs/basic_load_libs#limitations

Also, google is changing how the serve up assets so this is breaking charts; ie: I was calling out version 1.2 and it broke my charts for a few days.

https://github.com/google/google-visualization-issues/issues/2819

What do you think?

**Comment by kyleoliveira** [comment]
It's been quite a bit since I've poked at this and I never quite sorted it out anyhow 🤷‍♂️ I'm going to go ahead and close this off for now, but if new versions are working better I think that's great news!

**Pull request closed without merging**
